name: test

on:
  push:
    branches:
      - "**"
    tags:
      - "!v*"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ["oldstable", "stable"]

    steps:
      - uses: actions/checkout@v3
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
          cache: true

      - name: Install mage
        run: |
          mkdir mkdir -p /tmp/mage && cd /tmp/mage
          gh api repos/magefile/mage/releases/latest --jq '.assets[].browser_download_url' | grep _Linux-64bit.tar.gz | xargs -I '{}' curl -sL '{}' | tar -zxf -
          cp mage "/usr/local/bin/mage"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Test with mage
        run: mage test

      - name: Cresate snapshot
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: --snapshot --skip-publish --rm-dist -p 1
